#!/bin/bash

set -euo pipefail

SOURCE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

NUM_NODES=${NUM_NODES:-32}
GPUS_PER_NODE=${GPUS_PER_NODE:-4}
TIME_LIMIT=${TIME_LIMIT:-3h}
QUEUE=${QUEUE:-pbatch}
JOB_NAME=${JOB_NAME:-llama3-zero3}

APP_ID=${APP_ID:-llama3-1b}
DFTRACER_ENABLE=${DFTRACER_ENABLE:-1}
DFTRACER_INC_METADATA=${DFTRACER_INC_METADATA:-1}
DFTRACER_TRACE_COMPRESSION=${DFTRACER_TRACE_COMPRESSION:-1}
DFTRACER_ENABLE_AGGREGATION=${DFTRACER_ENABLE_AGGREGATION:-0}
DFTRACER_AGGREGATION_TYPE=${DFTRACER_AGGREGATION_TYPE:-FULL}
DFTRACER_TRACE_INTERVAL_MS=${DFTRACER_TRACE_INTERVAL_MS:-1000}
DFTRACER_AGGREGATION_FILE=${DFTRACER_AGGREGATION_FILE:-}
PRETOKENIZE_NUM_PROC=${PRETOKENIZE_NUM_PROC:-8}
PRETOKENIZE_WAIT_SECONDS=${PRETOKENIZE_WAIT_SECONDS:-7200}

MICRO_BATCH_SIZE_PER_GPU=${MICRO_BATCH_SIZE_PER_GPU:-64}
GRADIENT_ACCUMULATION_STEPS=${GRADIENT_ACCUMULATION_STEPS:-1}
MAX_SEQ_LENGTH=${MAX_SEQ_LENGTH:-128}
TRACK_STEP_PER_N=${TRACK_STEP_PER_N:-20}
SAVE_STEPS=${SAVE_STEPS:-1000}
NUM_EPOCHS=${NUM_EPOCHS:-1}
ENABLE_SEQUENCE_PACKING=${ENABLE_SEQUENCE_PACKING:-0}
MODEL_ID=${MODEL_ID:-meta-llama/Llama-3.2-1B}
LOCAL_MODEL_PATH=${LOCAL_MODEL_PATH:-/usr/WS2/sinurat1/LLM-Checkpoints/llama-3-1B}

FLUX_LOG_DIR="${SOURCE_DIR}/flux_outputs/${APP_ID}"
mkdir -p "${FLUX_LOG_DIR}"

jobid=$(flux --parent batch \
  -N "${NUM_NODES}" \
  --queue="${QUEUE}" \
  --exclusive \
  -o fastload=on \
  --time-limit="${TIME_LIMIT}" \
  --job-name="${JOB_NAME}" \
  --env=NUM_NODES="${NUM_NODES}" \
  --env=GPUS_PER_NODE="${GPUS_PER_NODE}" \
  --env=APP_ID="${APP_ID}" \
  --env=DFTRACER_ENABLE="${DFTRACER_ENABLE}" \
  --env=DFTRACER_INC_METADATA="${DFTRACER_INC_METADATA}" \
  --env=DFTRACER_TRACE_COMPRESSION="${DFTRACER_TRACE_COMPRESSION}" \
  --env=DFTRACER_ENABLE_AGGREGATION="${DFTRACER_ENABLE_AGGREGATION}" \
  --env=DFTRACER_AGGREGATION_TYPE="${DFTRACER_AGGREGATION_TYPE}" \
  --env=DFTRACER_TRACE_INTERVAL_MS="${DFTRACER_TRACE_INTERVAL_MS}" \
  --env=DFTRACER_AGGREGATION_FILE="${DFTRACER_AGGREGATION_FILE}" \
  --env=PRETOKENIZE_NUM_PROC="${PRETOKENIZE_NUM_PROC}" \
  --env=PRETOKENIZE_WAIT_SECONDS="${PRETOKENIZE_WAIT_SECONDS}" \
  --env=MICRO_BATCH_SIZE_PER_GPU="${MICRO_BATCH_SIZE_PER_GPU}" \
  --env=GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS}" \
  --env=MAX_SEQ_LENGTH="${MAX_SEQ_LENGTH}" \
  --env=TRACK_STEP_PER_N="${TRACK_STEP_PER_N}" \
  --env=SAVE_STEPS="${SAVE_STEPS}" \
  --env=NUM_EPOCHS="${NUM_EPOCHS}" \
  --env=ENABLE_SEQUENCE_PACKING="${ENABLE_SEQUENCE_PACKING}" \
  --env=MODEL_ID="${MODEL_ID}" \
  --env=LOCAL_MODEL_PATH="${LOCAL_MODEL_PATH}" \
  --output="${FLUX_LOG_DIR}/{{name}}-jobid_{{id}}-nodes_{{size}}.out" \
  "${SOURCE_DIR}/script_llama_zero3_ray.sh")

echo "Queued experiment job: ${JOB_NAME}, job ID: ${jobid}"
